---
helmDefaults:
  atomic: true
  force: false
  timeout: 120
  wait: true

releases:
  - name: postgres
    chart: bitnami/postgresql
    version: 10.16.1
    namespace: default
    values:
      - "../config/postgres.yaml"
