---
helmDefaults:
  atomic: false
  force: false
  timeout: 60
  wait: true

releases:
  - name: spring-petclinic
    chart: ../charts/spring-petclinic
    namespace: default
    values:
      - "../charts/spring-petclinic/values.yaml"
    set:
      - name: namespace
        value: default
