---
helmDefaults:
  atomic: true
  force: false
  timeout: 120
  wait: true

releases:
  - name: spring-petclinic
    chart: ../charts/spring-petclinic
    namespace: default
      #    values:
      #      - "../config/default/jenkins-config.yaml"
      #    set:
      #      - name: namespace
      #        value: default
