apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spring-petclinic.fullname" . }}-secret
  labels:
    {{- include "spring-petclinic.labels" . | nindent 4 }}
# type: servicebinding.io/postgresql
data:
  username: {{ default "petclinic" .Values.db.username | b64enc | quote }}
  password: {{ default "petclinic" .Values.db.password | b64enc | quote }}
  type: {{ default "postgresql" .Values.db.type | b64enc | quote }}
  host: {{ default "" .Values.db.host | b64enc | quote }}
  database: {{ default "" .Values.db.database | b64enc | quote }}
  port: {{ default "5432" .Values.db.port | b64enc | quote }}
