apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spring-petclinic.fullname" . }}-secret
  labels:
    {{- include "spring-petclinic.labels" . | nindent 4 }}
stringData:
  hostname: postgres
  username: petclinic
  type: postgresql
  url: jdbc:postgresql://postgres-postgresql.default.svc.cluster.local/petclinic
  port: 5432
